<script>
<p t="PROJECTNAME">TESTPROJECT</p>
<p t="SUBJECTNAME">TESTSUBJECT</p>
<e en="T" t="00104000" n="PatientComments">@always()Project:@param(@PROJECTNAME) Subject:@param(@SUBJECTNAME)-@date() Session:@param(@SUBJECTNAME)-@date()T@time()</e>
<e en="T" t="00081030" n="StudyDescription">@always()@param(@PROJECTNAME)</e>
<e en="T" t="00100010" n="PatientName">@always()@param(@SUBJECTNAME)-@date()</e>
<e en="T" t="00100020" n="PatientID">@always()@param(@SUBJECTNAME)-@date()T@time()</e>
</script>