name: Run test upload

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Run test upload
      run: |
        docker build . -t mirc-ctp:tester
        docker run mirc-ctp:tester
