name: Run test upload

on:
  workflow_dispatch:

jobs:
  Run:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build ctp runner
      run: docker build . -t mirc-ctp:tester
    - name: Run test upload
      run: docker run mirc-ctp:tester
